/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "on-background": "var(--on-background)",
        surface: "var(--surface)",
        "on-surface": "var(--on-surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container-highest": "var(--surface-container-highest)",
        primary: "var(--primary)",
        "on-primary": "var(--on-primary)",
        "primary-container": "var(--primary-container)",
        secondary: "var(--secondary)",
        "on-secondary": "var(--on-secondary)",
        tertiary: "var(--tertiary)",
        "on-tertiary": "var(--on-tertiary)",
        outline: "var(--outline)",
        "outline-variant": "var(--outline-variant)",
        "primary-fixed-dim": "#c0c1ff",
        "secondary-container": "#00a572",
        "on-surface-variant": "var(--on-surface-variant)",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-container": "#5c0008",
        "surface-variant": "#353534",
        "on-tertiary-fixed": "#410004",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#930013",
        "inverse-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "error-container": "#93000a",
        "on-primary-fixed": "#07006c",
        "secondary-fixed-dim": "#4edea3",
        "inverse-primary": "#494bd6",
        "secondary-fixed": "#6ffbbe",
        "surface-tint": "#c0c1ff",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#ffdad7",
        "on-primary-container": "#0d0096",
        "surface-bright": "#393939",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-container": "#00311f",
        error: "#ffb4ab",
        "tertiary-container": "#ff5451",
        "on-secondary-fixed": "#002113",
        "tertiary-fixed-dim": "#ffb3ad",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        label: ["Outfit", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 20px 40px rgba(242, 242, 242, 0.04)",
      },
      transitionTimingFunction: {
        expressive: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

